Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,88 +1,88 @@
-# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
+# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
+# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
 
-name: Node.js CI
+# name: Node.js CI
 
-on:
-  push:
-    branches: [ master ]
+# on:
+#   push:
+#     branches: [ master ]
 
-jobs:
-  build:
+# jobs:
+#   build:
 
-    runs-on: ${{ matrix.os }}
-    env:
-      CI: false
-    strategy:
-      matrix:
-        node-version: [12.6]
-        os: [ubuntu-latest, macOS-latest]
+#     runs-on: ${{ matrix.os }}
+#     env:
+#       CI: false
+#     strategy:
+#       matrix:
+#         node-version: [12.6]
+#         os: [ubuntu-latest, macOS-latest]
 
-    steps:
-    - uses: actions/checkout@v2
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v1
-      with:
-        node-version: ${{ matrix.node-version }}
-    - run: |
-        node --version
-        npm --version
+#     steps:
+#     - uses: actions/checkout@v2
+#     - name: Use Node.js ${{ matrix.node-version }}
+#       uses: actions/setup-node@v1
+#       with:
+#         node-version: ${{ matrix.node-version }}
+#     - run: |
+#         node --version
+#         npm --version
     
-    - name: npm install
-      run: npm ci
+#     - name: npm install
+#       run: npm ci
       
-    - name: build linux and mac
-      id: build
-      run: |
-        npm run electron-pack
+#     - name: build linux and mac
+#       id: build
+#       run: |
+#         npm run electron-pack
         
-    - name: Cleanup artifacts
-      run: |
-        npx rimraf "dist/!(*.deb|*.AppImage|*.dmg)"
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v1
-      with:
-        name: ${{ matrix.os }}
-        path: dist
+#     - name: Cleanup artifacts
+#       run: |
+#         npx rimraf "dist/!(*.deb|*.AppImage|*.dmg)"
+#     - name: Upload artifacts
+#       uses: actions/upload-artifact@v1
+#       with:
+#         name: ${{ matrix.os }}
+#         path: dist
 
-  build-windows:
-      runs-on: ${{ matrix.os }}
-      env:
-        CI: false
-      strategy:
-        matrix:
-          node-version: [12.6]
-          os: [windows-latest]
-      steps:
-      - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{ matrix.node-version }}
-      - run: |
-          node --version
-          npm --version
+#   build-windows:
+#       runs-on: ${{ matrix.os }}
+#       env:
+#         CI: false
+#       strategy:
+#         matrix:
+#           node-version: [12.6]
+#           os: [windows-latest]
+#       steps:
+#       - uses: actions/checkout@v2
+#       - name: Use Node.js ${{ matrix.node-version }}
+#         uses: actions/setup-node@v1
+#         with:
+#           node-version: ${{ matrix.node-version }}
+#       - run: |
+#           node --version
+#           npm --version
            
-      - name: npm install
-        run: npm ci
+#       - name: npm install
+#         run: npm ci
       
-      - name: build linux and mac
-        id: build
-        run: |
-          npm run electron-pack
+#       - name: build linux and mac
+#         id: build
+#         run: |
+#           npm run electron-pack
         
-      - name: Cleanup artifacts
-        if: matrix.os != 'windows-latest'
-        run: |
-          mkdir artifacts
-          mv "dist/(*.exe,*.deb,*.AppImage,*.dmg)" artifacts || true
-      - name: Cleanup artifacts Win
-        if: matrix.os == 'windows-latest'
-        run: |
-          mkdir artifacts
-          mv dist/*.exe artifacts
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v1
-        with:
-          name: ${{matrix.os}}
-          path: artifacts
+#       - name: Cleanup artifacts
+#         if: matrix.os != 'windows-latest'
+#         run: |
+#           mkdir artifacts
+#           mv "dist/(*.exe,*.deb,*.AppImage,*.dmg)" artifacts || true
+#       - name: Cleanup artifacts Win
+#         if: matrix.os == 'windows-latest'
+#         run: |
+#           mkdir artifacts
+#           mv dist/*.exe artifacts
+#       - name: Upload artifacts
+#         uses: actions/upload-artifact@v1
+#         with:
+#           name: ${{matrix.os}}
+#           path: artifacts
